# Generated by Django 4.0.3 on 2022-12-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='college_id',
        ),
    ]
